### ISSUE TITLE
 session.getRemote().sendString(String.valueOf( new JSONObject()

### ISSUE THREAD

**Issue by parthdarji** [tipsy/spark-websocket#1]
I get an error of new JSONObject()
Error:
Constructor JSONObject in class JSONObject can not be applied to given type: Required Map<String,Object>

How to solve this error

**Comment by tipsy** [comment]
Are you using `import org.json.JSONObject;` ?

**Comment by parthdarji** [comment]
Still it shows Can not find symbol:
Method getRemote()

**Comment by tipsy** [comment]
You need all these imports: 

```
import org.eclipse.jetty.websocket.api.*;
import org.json.*;
import java.text.*;
import java.util.*;
import static j2html.TagCreator.*;
import static spark.Spark.*;
```

I left the imports out from the tutorial, but if you clone the project and run it everything should work.

**Comment by tipsy** [comment]
@parthdarji Did you get it working when adding the imports?

**Comment by parthdarji** [comment]
yes, but there is something wrong with my code and i get error. Therefore,
i gave up because i don't understand where the problem is and which
resources I used to solve it.

Please see attached file.

If you help me, it's my please to get knowledge of Spring from you.

**Comment by tipsy** [comment]
There are no attached files here.. Anyway, if you just clone the repo it will work, then you can extend your application later :)

**Comment by parthdarji** [comment]
Yes, I know. I copied the code and i got an error when i run chat.java and open browser with localhost:4567/Chat

please see this link this is an error message

![capture](https://cloud.githubusercontent.com/assets/16583691/13657806/241ed732-e640-11e5-9cd3-44a970603b5b.PNG)

**Comment by tipsy** [comment]
Just go to `localhost:4567/`. The `/chat` is for the WebSocket.

**Comment by parthdarji** [comment]
Still i got the same error

![capture](https://cloud.githubusercontent.com/assets/16583691/13707486/e814f4a4-e777-11e5-8b06-07937968abed.PNG)
